

export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_SINGLE_PRODUCT = "SET_SINGLE_PRODUCT"
export const SET_RESOURCES = "SET_RESOURCES"
export const PROD_LOADING = "PROD_LOADING"
export const PROD_ERROR = "PROD_ERROR"
